version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=${MONGODB_URL}
  mongo:
    image: mongo
    ports:
      - "27017:27017"
